<a href="https://colab.research.google.com/github/nhatduong01/SQL_on_BigQuery/blob/main/Basis/BigQuery_and_SQL_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Using the data of The Chicago Police station in 2015

In [ ]:
from google.colab import auth
auth.authenticate_user()
print('Authenticated')

Authenticated

In [ ]:
import os
os.environ["GCLOUD_PROJECT"] = "BigQuerySQLExercises"

In [ ]:
from google.cloud import bigquery

# Create a "Client" object
client = bigquery.Client()
data_ref = client.dataset("nhtsa_traffic_fatalities", 
                          project="bigquery-public-data")
dataset = client.get_dataset(data_ref)

# Print all the tables in the dataset
tables = list(client.list_tables(dataset))

for table in tables:
  print(table.table_id)

accident_2015
accident_2016
cevent_2015
cevent_2016
damage_2015
damage_2016
distract_2015
distract_2016
drimpair_2015
drimpair_2016
factor_2015
factor_2016
maneuver_2015
maneuver_2016
nmcrash_2015
nmcrash_2016
nmimpair_2015
nmimpair_2016
nmprior_2015
nmprior_2016
parkwork_2015
parkwork_2016
pbtype_2015
pbtype_2016
person_2015
person_2016
safetyeq_2015
safetyeq_2016
vehicle_2015
vehicle_2016
vevent_2015
vevent_2016
vindecode_2015
vindecode_2016
violatn_2015
violatn_2016
vision_2015
vision_2016
vsoe_2015
vsoe_2016

In [ ]:
table_ref = data_ref.table('accident_2015')

table = client.get_table(table_ref)

# Print the table
client.list_rows(table, max_results = 5).to_dataframe()

   state_number state_name  ...  number_of_drunk_drivers        timestamp_of_crash
0            19       Iowa  ...                        1 2015-09-11 20:20:00+00:00
1            19       Iowa  ...                        1 2015-11-01 00:30:00+00:00
2            19       Iowa  ...                        0 2015-05-04 16:18:00+00:00
3            19       Iowa  ...                        0 2015-11-17 12:26:00+00:00
4            19       Iowa  ...                        0 2015-10-31 04:49:00+00:00

[5 rows x 70 columns]

### Determine the day in week which has the most accidents happened

In [ ]:
query = """
        SELECT COUNT(1) AS Num_accidents,
        day_of_week AS Day
        FROM `bigquery-public-data.nhtsa_traffic_fatalities.accident_2016`
        GROUP BY day_of_week
        ORDER BY Num_accidents DESC"""
query_job = client.query(query= query, project= 'bigquerysqlexercises')
accidents_by_days = query_job.to_dataframe()
accidents_by_days

   Num_accidents  Day
0           6159    7
1           5397    6
2           5353    1
3           4706    5
4           4537    2
5           4439    4
6           4157    3